### ISSUE TITLE
Exception when image generation options are used

### ISSUE THREAD

**Issue by Jens-H** [taylorwood/clj.native-image#1]
I get following error calling the clj.native-image function like this:
`clj -A:native-image -m clj.native-image core ~/Downloads/graalvm/bin/native-image --verbose`
Loading core
Compiling core
Building native image 'core' with classpath 'classes:src:/home/j/.m2/repository/org/clojure/clojure/1.9.0/clojure-1.9.0.jar:/home/j/.m2/repository/org/clojure/spec.alpha/0.1.143/spec.alpha-0.1.143.jar:/home/j/.m2/repository/org/clojure/core.specs.alpha/0.1.24/core.specs.alpha-0.1.24.jar'
Exception in thread "main" java.lang.ClassCastException: java.base/java.lang.String cannot be cast to clojure.lang.IPersistentCollection
	at clojure.core$conj__5112.invokeStatic(core.clj:82)
	at clojure.core$conj__5112.invoke(core.clj:82)
	at clj.native_image$build_native_image.invokeStatic(native_image.clj:30)
	at clj.native_image$build_native_image.invoke(native_image.clj:27)
	at clj.native_image$_main.invokeStatic(native_image.clj:53)
	at clj.native_image$_main.doInvoke(native_image.clj:40)
	at clojure.lang.RestFn.applyTo(RestFn.java:139)
	at clojure.lang.Var.applyTo(Var.java:702)
	at clojure.core$apply.invokeStatic(core.clj:657)
	at clojure.main$main_opt.invokeStatic(main.clj:317)
	at clojure.main$main_opt.invoke(main.clj:313)
	at clojure.main$main.invokeStatic(main.clj:424)
	at clojure.main$main.doInvoke(main.clj:387)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:702)
	at clojure.main.main(main.java:37)

Looking in line 30, I can see this conj failing: 
`(conj opts "--no-server")`

I guess the opts is a string here and not something that can be used with conj.

Thanks for making this repo!

**Comment by taylorwood** [comment]
@Jens-H thanks for trying this out and taking time to file an issue! I tested with a varying number of `native-image` flags, and with none—should be all good now.
